# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_game', '0002_auto_20161205_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_id',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
