# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_game', '0003_auto_20161205_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='p_block',
        ),
        migrations.AddField(
            model_name='person',
            name='block',
            field=models.CharField(default='3', max_length=1),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
