# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_game', '0005_auto_20161205_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('active_score', models.IntegerField(default=0, max_length=10)),
                ('high_score', models.IntegerField(default=0, max_length=10)),
            ],
        ),
    ]
