# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_game', '0007_auto_20161206_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_log', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='scorekeeper',
            name='username',
            field=models.CharField(default='Guest', max_length=10),
        ),
    ]
